/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for BatchStatus.
 */
public enum BatchStatus {
    /** Enum value pending. */
    PENDING("pending"),

    /** Enum value finished. */
    FINISHED("finished");

    /** The actual serialized value for a BatchStatus instance. */
    private String value;

    BatchStatus(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a BatchStatus instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed BatchStatus object, or null if unable to parse.
     */
    @JsonCreator
    public static BatchStatus fromString(String value) {
        BatchStatus[] items = BatchStatus.values();
        for (BatchStatus item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
