/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import java.util.UUID;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Report indicating if a batch has been successfully submitted, providing an
 * endpoint to monitor batch progress.
 */
public class BatchStartReportResponse {
    /**
     * indicates that that batch was successfully submitted.
     */
    @JsonProperty(value = "success")
    private Boolean success;

    /**
     * if the batch was not submitted successfully, there will be an error
     * message.
     */
    @JsonProperty(value = "error")
    private String error;

    /**
     * the id of the batch.
     */
    @JsonProperty(value = "id")
    private UUID id;

    /**
     * if the batch was submitted successfully, the url of an endpoint for
     * checking batch progress.
     */
    @JsonProperty(value = "statusEndpoint")
    private String statusEndpoint;

    /**
     * if the batch was submitted successfully, a list of the ids of submitted
     * operations,
     * in the same order as the submitted operations.
     */
    @JsonProperty(value = "operationIds")
    private List<UUID> operationIds;

    /**
     * Get indicates that that batch was successfully submitted.
     *
     * @return the success value
     */
    public Boolean success() {
        return this.success;
    }

    /**
     * Set indicates that that batch was successfully submitted.
     *
     * @param success the success value to set
     * @return the BatchStartReportResponse object itself.
     */
    public BatchStartReportResponse withSuccess(Boolean success) {
        this.success = success;
        return this;
    }

    /**
     * Get if the batch was not submitted successfully, there will be an error message.
     *
     * @return the error value
     */
    public String error() {
        return this.error;
    }

    /**
     * Set if the batch was not submitted successfully, there will be an error message.
     *
     * @param error the error value to set
     * @return the BatchStartReportResponse object itself.
     */
    public BatchStartReportResponse withError(String error) {
        this.error = error;
        return this;
    }

    /**
     * Get the id of the batch.
     *
     * @return the id value
     */
    public UUID id() {
        return this.id;
    }

    /**
     * Set the id of the batch.
     *
     * @param id the id value to set
     * @return the BatchStartReportResponse object itself.
     */
    public BatchStartReportResponse withId(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get if the batch was submitted successfully, the url of an endpoint for checking batch progress.
     *
     * @return the statusEndpoint value
     */
    public String statusEndpoint() {
        return this.statusEndpoint;
    }

    /**
     * Set if the batch was submitted successfully, the url of an endpoint for checking batch progress.
     *
     * @param statusEndpoint the statusEndpoint value to set
     * @return the BatchStartReportResponse object itself.
     */
    public BatchStartReportResponse withStatusEndpoint(String statusEndpoint) {
        this.statusEndpoint = statusEndpoint;
        return this;
    }

    /**
     * Get if the batch was submitted successfully, a list of the ids of submitted operations,
     in the same order as the submitted operations.
     *
     * @return the operationIds value
     */
    public List<UUID> operationIds() {
        return this.operationIds;
    }

    /**
     * Set if the batch was submitted successfully, a list of the ids of submitted operations,
     in the same order as the submitted operations.
     *
     * @param operationIds the operationIds value to set
     * @return the BatchStartReportResponse object itself.
     */
    public BatchStartReportResponse withOperationIds(List<UUID> operationIds) {
        this.operationIds = operationIds;
        return this;
    }

}
