/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Object used to represent border thickness.
 */
public class Bounds {
    /**
     * Width of top border.
     */
    @JsonProperty(value = "top", required = true)
    private int top;

    /**
     * Width of left border.
     */
    @JsonProperty(value = "left", required = true)
    private int left;

    /**
     * Width of bottom border.
     */
    @JsonProperty(value = "bottom", required = true)
    private int bottom;

    /**
     * Width of right border.
     */
    @JsonProperty(value = "right", required = true)
    private int right;

    /**
     * Get width of top border.
     *
     * @return the top value
     */
    public int top() {
        return this.top;
    }

    /**
     * Set width of top border.
     *
     * @param top the top value to set
     * @return the Bounds object itself.
     */
    public Bounds withTop(int top) {
        this.top = top;
        return this;
    }

    /**
     * Get width of left border.
     *
     * @return the left value
     */
    public int left() {
        return this.left;
    }

    /**
     * Set width of left border.
     *
     * @param left the left value to set
     * @return the Bounds object itself.
     */
    public Bounds withLeft(int left) {
        this.left = left;
        return this;
    }

    /**
     * Get width of bottom border.
     *
     * @return the bottom value
     */
    public int bottom() {
        return this.bottom;
    }

    /**
     * Set width of bottom border.
     *
     * @param bottom the bottom value to set
     * @return the Bounds object itself.
     */
    public Bounds withBottom(int bottom) {
        this.bottom = bottom;
        return this;
    }

    /**
     * Get width of right border.
     *
     * @return the right value
     */
    public int right() {
        return this.right;
    }

    /**
     * Set width of right border.
     *
     * @param right the right value to set
     * @return the Bounds object itself.
     */
    public Bounds withRight(int right) {
        this.right = right;
        return this;
    }

}
