/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Representation of an RGB color.
 */
public class Color {
    /**
     * The red component.
     */
    @JsonProperty(value = "r", required = true)
    private int r;

    /**
     * The green component.
     */
    @JsonProperty(value = "g", required = true)
    private int g;

    /**
     * The blue component.
     */
    @JsonProperty(value = "b", required = true)
    private int b;

    /**
     * Get the red component.
     *
     * @return the r value
     */
    public int r() {
        return this.r;
    }

    /**
     * Set the red component.
     *
     * @param r the r value to set
     * @return the Color object itself.
     */
    public Color withR(int r) {
        this.r = r;
        return this;
    }

    /**
     * Get the green component.
     *
     * @return the g value
     */
    public int g() {
        return this.g;
    }

    /**
     * Set the green component.
     *
     * @param g the g value to set
     * @return the Color object itself.
     */
    public Color withG(int g) {
        this.g = g;
        return this;
    }

    /**
     * Get the blue component.
     *
     * @return the b value
     */
    public int b() {
        return this.b;
    }

    /**
     * Set the blue component.
     *
     * @param b the b value to set
     * @return the Color object itself.
     */
    public Color withB(int b) {
        this.b = b;
        return this;
    }

}
