/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Output to Webp.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("ImageFormat_Webp")
public class ImageFormatWebp extends TransformUnit {
    /**
     * Webp compression level.
     */
    @JsonProperty(value = "quality")
    private Integer quality;

    /**
     * Get webp compression level.
     *
     * @return the quality value
     */
    public Integer quality() {
        return this.quality;
    }

    /**
     * Set webp compression level.
     *
     * @param quality the quality value to set
     * @return the ImageFormatWebp object itself.
     */
    public ImageFormatWebp withQuality(Integer quality) {
        this.quality = quality;
        return this;
    }

}
