/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * Output to Png.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("ImageFormat_Png")
public class ImageFormatPng extends TransformUnit {
    /**
     * Png compression level.
     */
    @JsonProperty(value = "compressionLevel")
    private Integer compressionLevel;

    /**
     * Create progressive/interlace scan png.
     */
    @JsonProperty(value = "progressive")
    private Boolean progressive;

    /**
     * Use adaptive row filtering.
     */
    @JsonProperty(value = "adaptiveFiltering")
    private Boolean adaptiveFiltering;

    /**
     * Get png compression level.
     *
     * @return the compressionLevel value
     */
    public Integer compressionLevel() {
        return this.compressionLevel;
    }

    /**
     * Set png compression level.
     *
     * @param compressionLevel the compressionLevel value to set
     * @return the ImageFormatPng object itself.
     */
    public ImageFormatPng withCompressionLevel(Integer compressionLevel) {
        this.compressionLevel = compressionLevel;
        return this;
    }

    /**
     * Get create progressive/interlace scan png.
     *
     * @return the progressive value
     */
    public Boolean progressive() {
        return this.progressive;
    }

    /**
     * Set create progressive/interlace scan png.
     *
     * @param progressive the progressive value to set
     * @return the ImageFormatPng object itself.
     */
    public ImageFormatPng withProgressive(Boolean progressive) {
        this.progressive = progressive;
        return this;
    }

    /**
     * Get use adaptive row filtering.
     *
     * @return the adaptiveFiltering value
     */
    public Boolean adaptiveFiltering() {
        return this.adaptiveFiltering;
    }

    /**
     * Set use adaptive row filtering.
     *
     * @param adaptiveFiltering the adaptiveFiltering value to set
     * @return the ImageFormatPng object itself.
     */
    public ImageFormatPng withAdaptiveFiltering(Boolean adaptiveFiltering) {
        this.adaptiveFiltering = adaptiveFiltering;
        return this;
    }

}
