/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for Strategy.
 */
public enum Strategy {
    /** Enum value attention. */
    ATTENTION("attention"),

    /** Enum value entropy. */
    ENTROPY("entropy");

    /** The actual serialized value for a Strategy instance. */
    private String value;

    Strategy(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a Strategy instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed Strategy object, or null if unable to parse.
     */
    @JsonCreator
    public static Strategy fromString(String value) {
        Strategy[] items = Strategy.values();
        for (Strategy item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
