/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Defines values for TiffPredictor.
 */
public enum TiffPredictor {
    /** Enum value horizontal. */
    HORIZONTAL("horizontal"),

    /** Enum value float. */
    FLOAT("float"),

    /** Enum value none. */
    NONE("none");

    /** The actual serialized value for a TiffPredictor instance. */
    private String value;

    TiffPredictor(String value) {
        this.value = value;
    }

    /**
     * Parses a serialized value to a TiffPredictor instance.
     *
     * @param value the serialized value to parse.
     * @return the parsed TiffPredictor object, or null if unable to parse.
     */
    @JsonCreator
    public static TiffPredictor fromString(String value) {
        TiffPredictor[] items = TiffPredictor.values();
        for (TiffPredictor item : items) {
            if (item.toString().equalsIgnoreCase(value)) {
                return item;
            }
        }
        return null;
    }

    @JsonValue
    @Override
    public String toString() {
        return this.value;
    }
}
