/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * A wrapped for RawTransformGraph instances, containing operation-specific
 * metadata.
 */
public class TransformGraphMetadataEnvelope {
    /**
     * The transform graph that represents the operation.
     */
    @JsonProperty(value = "graph")
    private TransformGraph graph;

    /**
     * The operation id of this operation.
     */
    @JsonProperty(value = "operationId")
    private UUID operationId;

    /**
     * The batch id of the batch containing this operation.
     */
    @JsonProperty(value = "batchId")
    private UUID batchId;

    /**
     * The account id of the account that will be/was charged for this
     * operation.
     */
    @JsonProperty(value = "accountId")
    private UUID accountId;

    /**
     * The user id of the user that submitted this batch.
     */
    @JsonProperty(value = "ownerId")
    private Integer ownerId;

    /**
     * Get the transform graph that represents the operation.
     *
     * @return the graph value
     */
    public TransformGraph graph() {
        return this.graph;
    }

    /**
     * Set the transform graph that represents the operation.
     *
     * @param graph the graph value to set
     * @return the TransformGraphMetadataEnvelope object itself.
     */
    public TransformGraphMetadataEnvelope withGraph(TransformGraph graph) {
        this.graph = graph;
        return this;
    }

    /**
     * Get the operation id of this operation.
     *
     * @return the operationId value
     */
    public UUID operationId() {
        return this.operationId;
    }

    /**
     * Set the operation id of this operation.
     *
     * @param operationId the operationId value to set
     * @return the TransformGraphMetadataEnvelope object itself.
     */
    public TransformGraphMetadataEnvelope withOperationId(UUID operationId) {
        this.operationId = operationId;
        return this;
    }

    /**
     * Get the batch id of the batch containing this operation.
     *
     * @return the batchId value
     */
    public UUID batchId() {
        return this.batchId;
    }

    /**
     * Set the batch id of the batch containing this operation.
     *
     * @param batchId the batchId value to set
     * @return the TransformGraphMetadataEnvelope object itself.
     */
    public TransformGraphMetadataEnvelope withBatchId(UUID batchId) {
        this.batchId = batchId;
        return this;
    }

    /**
     * Get the account id of the account that will be/was charged for this operation.
     *
     * @return the accountId value
     */
    public UUID accountId() {
        return this.accountId;
    }

    /**
     * Set the account id of the account that will be/was charged for this operation.
     *
     * @param accountId the accountId value to set
     * @return the TransformGraphMetadataEnvelope object itself.
     */
    public TransformGraphMetadataEnvelope withAccountId(UUID accountId) {
        this.accountId = accountId;
        return this;
    }

    /**
     * Get the user id of the user that submitted this batch.
     *
     * @return the ownerId value
     */
    public Integer ownerId() {
        return this.ownerId;
    }

    /**
     * Set the user id of the user that submitted this batch.
     *
     * @param ownerId the ownerId value to set
     * @return the TransformGraphMetadataEnvelope object itself.
     */
    public TransformGraphMetadataEnvelope withOwnerId(Integer ownerId) {
        this.ownerId = ownerId;
        return this;
    }

}
