/**
 * Code generated by Microsoft (R) AutoRest Code Generator.
 * Changes may cause incorrect behavior and will be lost if the code is
 * regenerated.
 */

package pixelshift.models;

import com.fasterxml.jackson.annotation.JsonTypeInfo;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonSubTypes;

/**
 * The TransformUnit model.
 */
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "kind")
@JsonTypeName("TransformUnit")
@JsonSubTypes({
    @JsonSubTypes.Type(name = "StorageSource_S3", value = StorageSourceS3.class),
    @JsonSubTypes.Type(name = "StorageSink_S3", value = StorageSinkS3.class),
    @JsonSubTypes.Type(name = "Image_Grayscale", value = ImageGrayscale.class),
    @JsonSubTypes.Type(name = "Image_Extend", value = ImageExtend.class),
    @JsonSubTypes.Type(name = "Image_ResizeAutoCrop", value = ImageResizeAutoCrop.class),
    @JsonSubTypes.Type(name = "Image_ResizeCrop", value = ImageResizeCrop.class),
    @JsonSubTypes.Type(name = "Image_ResizeMax", value = ImageResizeMax.class),
    @JsonSubTypes.Type(name = "Image_ResizeMin", value = ImageResizeMin.class),
    @JsonSubTypes.Type(name = "Image_ResizeToHeight", value = ImageResizeToHeight.class),
    @JsonSubTypes.Type(name = "Image_ResizeToWidth", value = ImageResizeToWidth.class),
    @JsonSubTypes.Type(name = "Image_Tint", value = ImageTint.class),
    @JsonSubTypes.Type(name = "ImageFormat_Jpeg", value = ImageFormatJpeg.class),
    @JsonSubTypes.Type(name = "ImageFormat_Png", value = ImageFormatPng.class),
    @JsonSubTypes.Type(name = "ImageFormat_Tiff", value = ImageFormatTiff.class),
    @JsonSubTypes.Type(name = "ImageFormat_Webp", value = ImageFormatWebp.class)
})
public class TransformUnit {
}
